[package]
name = "commenteer"
version = "0.2.0"
authors = ["Chad Baxter <cbaxter@mail.umw.edu>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
mime_guess = "1.8.6"
tempfile = "3.0.7"
walkdir = "2.2.7"
